# Generated by Django 3.2.9 on 2021-12-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriber_portal', '0006_alter_pdprescriber_isopioidprescriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdprescriber',
            options={'managed': False},
        ),
    ]
