# Generated by Django 3.2.9 on 2021-12-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriber_portal', '0007_alter_pdprescriber_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdprescriber',
            options={},
        ),
    ]
