# Generated by Django 3.2.9 on 2021-12-02 05:33

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview_img',
            field=models.ImageField(blank=True, null=True, upload_to='preview_img'),
        ),
        migrations.AddField(
            model_name='article',
            name='preview_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_type',
            field=models.CharField(choices=[('Article', 'Article'), ('Blog Post', 'Blog Post')], max_length=20),
        ),
    ]
