# Generated by Django 3.2.9 on 2021-12-03 21:30

from django.db import migrations, models
import django_quill.fields
import edu.models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_auto_20211202_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('body', django_quill.fields.QuillField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('internal_resource_link', models.CharField(blank=True, max_length=255, null=True)),
                ('external_resource_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='preview_img',
            field=models.ImageField(blank=True, null=True, upload_to=edu.models.Article.preview_img_path),
        ),
    ]
