# Generated by Django 3.2.9 on 2021-12-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0008_alter_fact_internal_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='internal_resource',
            field=models.ManyToManyField(blank=True, to='edu.Article', verbose_name='Internal Resources'),
        ),
    ]
