# Generated by Django 3.2.9 on 2021-12-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0009_alter_fact_internal_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fact',
            name='internal_resource',
        ),
        migrations.AddField(
            model_name='fact',
            name='internal_resources',
            field=models.ManyToManyField(blank=True, to='edu.Article'),
        ),
    ]
