# Generated by Django 3.2.9 on 2021-12-04 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0010_auto_20211203_2248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PdDrugs',
        ),
        migrations.DeleteModel(
            name='PdPrescriber',
        ),
        migrations.DeleteModel(
            name='PdStatedata',
        ),
        migrations.DeleteModel(
            name='PdTriple',
        ),
    ]
