# Generated by Django 3.2.9 on 2021-12-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0011_auto_20211204_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('quote', models.TextField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('external_resource_link', models.URLField(blank=True, null=True)),
                ('internal_resources', models.ManyToManyField(blank=True, to='edu.Article')),
            ],
        ),
    ]
