# Generated by Django 3.2.9 on 2021-12-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0012_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_type',
            field=models.CharField(choices=[('Article', 'Article'), ('Blog', 'Blog'), ('Local Resource', 'Local Resource')], max_length=20),
        ),
    ]
