# Generated by Django 3.2.9 on 2021-12-06 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdTriple',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prescriberid', models.BigIntegerField()),
                ('drugname', models.CharField(max_length=30)),
                ('qty', models.IntegerField()),
            ],
            options={
                'db_table': 'pd_triple',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PdDrug',
            fields=[
                ('drugid', models.AutoField(primary_key=True, serialize=False)),
                ('drugname', models.CharField(max_length=30)),
                ('isopioid', models.BooleanField()),
            ],
            options={
                'db_table': 'pd_drug',
            },
        ),
        migrations.CreateModel(
            name='PdStatedata',
            fields=[
                ('state', models.CharField(max_length=14)),
                ('stateabbrev', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('population', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
            options={
                'db_table': 'pd_statedata',
            },
        ),
        migrations.CreateModel(
            name='PdPrescriber',
            fields=[
                ('npi', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('specialty', models.CharField(max_length=200)),
                ('isopioidprescriber', models.BooleanField()),
                ('totalprescriptions', models.IntegerField()),
                ('state', models.ForeignKey(db_column='state', on_delete=django.db.models.deletion.DO_NOTHING, to='prescriber_portal.pdstatedata')),
            ],
            options={
                'db_table': 'pd_prescriber',
            },
        ),
        migrations.CreateModel(
            name='PdCredential',
            fields=[
                ('npi', models.BigIntegerField(primary_key=True, serialize=False)),
                ('credential', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'pd_credential',
                'unique_together': {('npi', 'credential')},
            },
        ),
        migrations.CreateModel(
            name='PdPrescriptionquantity',
            fields=[
                ('npi', models.BigIntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('drugid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prescriber_portal.pddrug')),
            ],
            options={
                'db_table': 'pd_prescriptionquantity',
                'unique_together': {('npi', 'drugid')},
            },
        ),
    ]
