# Generated by Django 3.2.9 on 2021-12-04 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriber_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdstatedata',
            options={},
        ),
    ]
