# Generated by Django 3.2.9 on 2021-12-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriber_portal', '0005_alter_pdprescriber_isopioidprescriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdprescriber',
            name='isopioidprescriber',
            field=models.BooleanField(),
        ),
    ]
