# Generated by Django 3.2.8 on 2021-12-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriber_portal', '0006_alter_pdprescriber_isopioidprescriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdprescriber',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='pddrug',
            name='drugid',
            field=models.AutoField(db_column='drugid', primary_key=True, serialize=False),
        ),
    ]
