# Generated by Django 3.2.8 on 2021-12-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriber_portal', '0007_auto_20211207_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdprescriber',
            options={},
        ),
    ]
