# Generated by Django 3.2.9 on 2021-12-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriber_portal', '0008_alter_pdprescriber_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdprescriber',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pdprescriptionquantity',
            options={'managed': False},
        ),
    ]
