# Generated by Django 3.2.9 on 2021-12-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriber_portal', '0012_auto_20211207_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdprescriber',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='pdstatedata',
            name='state',
            field=models.CharField(db_column='state', max_length=14),
        ),
    ]
