# Generated by Django 3.2.9 on 2021-12-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriber_portal', '0013_auto_20211207_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdprescriber',
            options={},
        ),
    ]
